// Music: a licensed library (tracks you upload, with BPM + beat-grid metadata)
// plus the built-in composer, which scores each reel to its own cut.
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { compose, encodeWav, MOODS, SFX_NAMES, sfx } from "../lib/audio-synth";
import { DATA_DIR, putFile, resolveFile } from "../lib/store";
import { MusicTrack, type BrandKit, type Storyboard, type Tone } from "../lib/schema";

const LIB = path.join(DATA_DIR, "music", "library.json");

const MOOD_TONES: Record<string, Tone[]> = {
  "airy-minimal": ["premium-minimal", "clean-clinical"],
  "luxe-noir": ["luxury", "premium-minimal"],
  "warm-organic": ["warm-natural"],
  "clean-pulse": ["clean-clinical", "techy"],
  "tech-drive": ["techy"],
  "bold-pop": ["playful-bold"],
};

export function composerTracks(): MusicTrack[] {
  return MOODS.map((m) => ({
    id: `composer:${m.id}`, title: `${m.title} (scored to the cut)`, bpm: m.bpm, mood: m.id, energy: m.energy, tones: MOOD_TONES[m.id] ?? [],
    beatGrid: { offsetSec: 0, beatsPerBar: 4 }, path: "", license: "Generated by ProductClips — owned, royalty-free",
  }));
}

export async function libraryTracks(): Promise<MusicTrack[]> {
  try { return (JSON.parse(await fs.readFile(LIB, "utf8")) as unknown[]).map((t) => MusicTrack.parse(t)); } catch { return []; }
}
export async function addLibraryTrack(t: Omit<MusicTrack, "id" | "path">, file: Buffer, ext: string) {
  const id = `lib:${crypto.randomBytes(5).toString("hex")}`;
  const p = await putFile(`music/${id.replace(":", "-")}.${ext}`, file);
  const all = await libraryTracks();
  const track = MusicTrack.parse({ ...t, id, path: p });
  all.push(track);
  await fs.mkdir(path.dirname(LIB), { recursive: true });
  await fs.writeFile(LIB, JSON.stringify(all, null, 2));
  return track;
}
export async function allTracks() { return [...composerTracks(), ...(await libraryTracks())]; }

/** Picks by tone and energy (premium-minimal ≈ 90–105 BPM airy, playful-bold ≈ 118–128 punchy). */
export async function pickTrack(kit: BrandKit): Promise<MusicTrack> {
  const tracks = await allTracks();
  const score = (t: MusicTrack) => (t.tones.includes(kit.tone) ? 10 : 0) - Math.abs(t.energy - kit.energy) * 2 + (t.id.startsWith("lib:") ? 1 : 0);
  return tracks.sort((a, b) => score(b) - score(a))[0];
}
export async function getTrack(id: string) { return (await allTracks()).find((t) => t.id === id) ?? composerTracks()[0]; }

/** Audio file for this storyboard. Composer tracks are rendered to the storyboard's sections. */
export async function ensureScore(projectId: string, sb: Storyboard): Promise<string | null> {
  const track = await getTrack(sb.musicTrackId);
  if (!track.id.startsWith("composer:")) return track.path || null;
  const mood = MOODS.find((m) => `composer:${m.id}` === track.id)!;
  const reveal = sb.scenes.find((s) => s.role === "reveal")?.startBeat ?? 4;
  const recap = sb.scenes.find((s) => s.role === "recap")?.startBeat ?? Math.round((21 * mood.bpm) / 60);
  const cta = sb.scenes.find((s) => s.role === "cta")?.startBeat ?? Math.round((24 * mood.bpm) / 60);
  const arr = { revealBeat: reveal, recapBeat: recap, ctaBeat: cta, totalBeats: Math.ceil((29 * mood.bpm) / 60) };
  const key = crypto.createHash("sha1").update(JSON.stringify({ m: mood.id, arr, v: 3 })).digest("hex").slice(0, 10);
  const rel = `projects/${projectId}/files/score-${key}.wav`;
  try { await fs.access(resolveFile(rel)); return rel; } catch { /* compose */ }
  const { l, r } = compose(mood, arr, parseInt(key.slice(0, 6), 16));
  await putFile(rel, encodeWav(l, r));
  return rel;
}

export async function ensureSfx() {
  for (const n of SFX_NAMES) {
    const rel = `sfx/${n}.wav`;
    try { await fs.access(resolveFile(rel)); } catch { await putFile(rel, encodeWav(sfx(n))); }
  }
}
